### ISSUE TITLE
NativeAOT not supported

### ISSUE THREAD

**Issue by kant2002** [JeremyKuhne/WInterop#8]
I found this excellent library, and decide play with it in NativeAOT.
Since this is thin wrapper agains Win32 API, I thought that it will just work.

Unfortunately I hit this line 

https://github.com/JeremyKuhne/WInterop/blob/6e5f832b96f4eaae886141af2b46bac2b700cc14/src/WInterop.Desktop/Windows/Classes/WindowClass.cs#L59

`Assembly.GetCallingAssembly()` does [not supported](https://github.com/dotnet/runtime/issues/69919) by NativeAOT.
Is there a way how code could be modified to better accomodate NativeAOT

I make run Clock sample with reflection disabled, by passing HINSTANCE of exe. Maybe you could find a better way. 
```csharp
// This was added.
public Clock()
    : base(moduleInstance: Modules.GetModuleHandle(null))
{
}
```

BTW: only 1.3 Mb resulting executable.

**Comment by JeremyKuhne** [comment]
@kant2002 Sorry about the delayed response. Here is the change I made: https://github.com/JeremyKuhne/WInterop/commit/a95a94dac9ebec55ec965136a1a8f97c805207bc

**Comment by kant2002** [comment]
No problem. Your library has very interesting properties, and so close to Win32. Thanks for pinging me. Let me try it out
